import Link from 'next/link'
import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { ContentCTA } from '@/components/content/ContentCTA'
import { getAllBlogPosts } from '@/lib/content'
import { blogTopics, blogTopic } from '@/lib/blog-topics'
import { buildMetadata } from '@/lib/seo'
export const metadata = buildMetadata({ title: 'Link Building Blog: Research, Outreach & Practical SEO', description: 'Explore practical backlink guides by topic: research, outreach, link quality, measurement and maintenance. Find useful tools and clear next steps for your site.', canonicalUrl: 'https://backlinkgrid.com/blog', type: 'website' })
export default function BlogPage() {
  const posts = getAllBlogPosts()
  const featured = ['verify-backlink-placement', 'backlinks-not-showing-google-search-console', 'preserve-backlinks-website-migration'].map(slug => posts.find(p => p.slug === slug)).filter(p => p !== undefined)
  return <><Header /><main className="pt-14 sm:pt-16 lg:pt-20 min-h-screen bg-surface-50">
    <header className="bg-white border-b border-surface-200"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-12 sm:py-16"><p className="text-sm font-semibold text-brand-red">The BacklinkGrid journal</p><h1 className="text-4xl sm:text-5xl font-bold tracking-tight max-w-3xl mt-4">Build better links.<br />Know what to check next.</h1><p className="text-lg text-surface-600 mt-6 max-w-2xl leading-relaxed">Practical guides for finding opportunities, earning useful placements and looking after the links you already have.</p><nav aria-label="Blog topics" className="flex flex-wrap gap-x-6 gap-y-3 mt-8 text-sm">{blogTopics.map(topic => <a className="underline underline-offset-4 text-surface-700 hover:text-brand-red" key={topic.id} href={`#${topic.id}`}>{topic.label}</a>)}</nav></div></header>
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14"><section aria-labelledby="featured-reading"><h2 id="featured-reading" className="text-2xl font-bold">Start with a practical check</h2><div className="grid md:grid-cols-3 gap-8 mt-6">{featured.map(post => <Link key={post.slug} href={`/blog/${post.slug}`} className="group border-t-2 border-surface-950 py-5"><h3 className="font-bold text-xl leading-snug group-hover:text-brand-red transition-colors">{post.title}</h3><p className="text-sm text-surface-600 leading-relaxed mt-3">{post.description}</p><span className="block mt-4 text-sm font-semibold">Read the guide →</span></Link>)}</div></section>
      {blogTopics.map(topic => <section id={topic.id} key={topic.id} className="scroll-mt-40 border-t border-surface-300 pt-8 mt-12"><div className="sm:flex justify-between gap-8 items-start"><div><h2 className="font-bold text-2xl">{topic.label}</h2><p className="text-sm text-surface-600 mt-2">{topic.description}</p></div><Link className="inline-block mt-3 sm:mt-1 text-sm underline underline-offset-4 shrink-0" href={topic.hub}>Explore the topic hub →</Link></div><ul className="grid md:grid-cols-2 gap-x-10 mt-5">{posts.filter(post => blogTopic(post.slug).id === topic.id).map(post => <li key={post.slug} className="border-b border-surface-200 py-4"><Link className="font-medium leading-relaxed hover:text-brand-red transition-colors" href={`/blog/${post.slug}`}>{post.title}</Link><p className="text-xs text-surface-500 mt-1">{post.readingTime}</p></li>)}</ul></section>)}
      <div className="mt-14"><ContentCTA /></div><p className="mt-6 text-sm text-surface-600">Ready to apply what you have read? <Link className="underline" href="/tools">Try the free website tools</Link> or <Link className="underline" href="/templates">download a working template</Link>.</p>
    </div></main><Footer /></>
}
