export const industries = ['Software / SaaS', 'Developer tools', 'Local business', 'E-commerce', 'Design / creative', 'Content / publishing', 'Professional services']
type Opportunity = { name: string; url: string; industries: string[]; keywords: string[]; eligibility: string; steps: string; fee: string; variable?: boolean }
// Deliberately limited public selection. The paid research file is never imported into a client bundle.
export const opportunities: Opportunity[] = [
  { name: 'Product Hunt', url: 'https://www.producthunt.com/posts/new', industries: ['Software / SaaS', 'Developer tools'], keywords: ['app', 'software', 'product'], eligibility: 'A distinct product people can try; prepare an actual launch, not a directory-only submission.', steps: 'Create a maker profile, add the product URL, screenshots and a clear description. Follow current launch guidelines.', fee: 'Recorded free submission route' },
  { name: 'Hacker News', url: 'https://news.ycombinator.com/submit', industries: ['Developer tools', 'Software / SaaS'], keywords: ['developer', 'open source', 'tool'], eligibility: 'A project the community can try or a genuinely interesting technical resource.', steps: 'Read the Show HN guidelines. Submit the project and be available to answer substantive questions.', fee: 'Recorded free submission route' },
  { name: 'GitHub', url: 'https://github.com/new', industries: ['Developer tools'], keywords: ['api', 'open source', 'developer', 'code'], eligibility: 'A real repository, useful open-source project or developer resource; not a promotional empty repository.', steps: 'Publish useful code or documentation, write a complete README and add the relevant project website.', fee: 'Recorded free public repository route' },
  { name: 'LinkedIn', url: 'https://www.linkedin.com/company/setup/new/', industries, keywords: ['business', 'company', 'consulting'], eligibility: 'A legitimate business or organisation with an authorised page administrator.', steps: 'Create a company page with consistent branding, website, description and business information.', fee: 'Recorded free company-page route' },
  { name: 'G2', url: 'https://sell.g2.com/create-a-profile', industries: ['Software / SaaS'], keywords: ['software', 'saas', 'platform'], eligibility: 'A software product fitting G2’s categories; listing and review policies apply.', steps: 'Use G2’s vendor/product listing process. Supply product details and verify the current free listing terms.', fee: 'Recorded free basic listing; paid upgrades separate' },
  { name: 'Capterra', url: 'https://www.capterra.com/vendors', industries: ['Software / SaaS'], keywords: ['software', 'management', 'platform'], eligibility: 'Business software in an accepted category; vendor review is required.', steps: 'Start the vendor listing process, choose an accurate category and supply product information.', fee: 'Recorded free basic listing; advertising separate' },
  { name: 'AlternativeTo', url: 'https://alternativeto.net/', industries: ['Software / SaaS', 'Developer tools'], keywords: ['app', 'software', 'alternative'], eligibility: 'A genuine application with a useful comparison to existing software.', steps: 'Create an account, suggest the application and describe its functions accurately. Respect community moderation.', fee: 'Recorded free suggestion route' },
  { name: 'SaaSHub', url: 'https://www.saashub.com/', industries: ['Software / SaaS'], keywords: ['saas', 'software', 'tool'], eligibility: 'A software product with a working public website.', steps: 'Find the product submission option, check for an existing listing and add accurate categories and details.', fee: 'Recorded free basic route; promoted options separate' },
  { name: 'DEV Community', url: 'https://dev.to/new', industries: ['Developer tools'], keywords: ['developer', 'programming', 'api'], eligibility: 'Original developer-focused writing that offers value beyond product promotion.', steps: 'Publish a useful tutorial or technical explanation. Link to your project where it supports the article.', fee: 'Recorded free publishing route' },
  { name: 'Hashnode', url: 'https://hashnode.com/', industries: ['Developer tools', 'Content / publishing'], keywords: ['developer', 'technical', 'blog'], eligibility: 'Substantive technical writing; avoid duplicate low-value promotional posts.', steps: 'Create a publication, write a useful technical article and include relevant source or project links.', fee: 'Recorded free basic publishing route' },
  { name: 'Trustpilot', url: 'https://business.trustpilot.com/', industries: ['E-commerce', 'Professional services', 'Local business'], keywords: ['shop', 'service', 'customer'], eligibility: 'A genuine business; review collection must follow the platform’s rules.', steps: 'Claim or create the business profile, verify ownership and complete accurate website details.', fee: 'Recorded free basic business route; paid features separate' },
  { name: 'Yelp', url: 'https://biz.yelp.com/', industries: ['Local business'], keywords: ['restaurant', 'local', 'salon', 'repair'], eligibility: 'An eligible local business in a market supported by Yelp.', steps: 'Check for an existing listing, claim it or add the business, then verify location and website details.', fee: 'Recorded free business listing route' },
  { name: 'Google Business Profile', url: 'https://www.google.com/business/', industries: ['Local business'], keywords: ['local', 'visit', 'service area', 'appointment'], eligibility: 'An eligible business that meets customers in person. Online-only businesses generally do not qualify.', steps: 'Check eligibility, claim or add the business and complete verification before adding the website.', fee: 'Recorded free profile route' },
  { name: 'Behance', url: 'https://www.behance.net/', industries: ['Design / creative'], keywords: ['design', 'portfolio', 'creative'], eligibility: 'Original visual creative work with appropriate ownership rights.', steps: 'Create a complete profile and publish an actual project case study with relevant website links.', fee: 'Recorded free basic portfolio route' },
  { name: 'Dribbble', url: 'https://dribbble.com/', industries: ['Design / creative'], keywords: ['design', 'designer', 'branding'], eligibility: 'Design work and a suitable professional profile; linking features and plans can vary.', steps: 'Review current membership and profile-link options before creating a portfolio.', fee: 'Variable: check the current plan', variable: true },
  { name: 'Pinterest', url: 'https://business.pinterest.com/', industries: ['E-commerce', 'Design / creative', 'Content / publishing'], keywords: ['shop', 'design', 'recipe', 'fashion'], eligibility: 'Useful visual content and a relevant destination page; avoid repetitive promotional pins.', steps: 'Create a business profile and original pins that lead to matching products or useful resources.', fee: 'Recorded free organic publishing route' },
  { name: 'Medium', url: 'https://medium.com/', industries: ['Content / publishing', 'Professional services'], keywords: ['article', 'writing', 'consulting', 'guide'], eligibility: 'Useful original writing that complies with Medium’s publishing policies.', steps: 'Complete your profile and write a substantive article. Add contextual links only where useful.', fee: 'Recorded free publishing route' },
  { name: 'Substack', url: 'https://substack.com/', industries: ['Content / publishing'], keywords: ['newsletter', 'writer', 'publication'], eligibility: 'A real publication or newsletter you intend to maintain.', steps: 'Set up a publication, write a useful introduction and add your website to relevant publication information.', fee: 'Recorded free publishing route; paid-subscription fees separate' },
]
export function matchOpportunities(industry: string, includeVariable: boolean, text: string) {
  if (!industries.includes(industry)) throw new Error('Choose a business type.')
  const lower = text.toLowerCase()
  return opportunities.filter(o => o.industries.includes(industry) && (includeVariable || !o.variable)).map(o => {
    const evidence = o.keywords.filter(k => lower.includes(k))
    return { ...o, evidence, score: (o.industries.length === 1 ? 3 : o.industries.length < 4 ? 2 : 0) + Math.min(evidence.length, 2) }
  }).sort((a, b) => b.score - a.score).slice(0, 5)
}
